spring:
  datasource:
    url: jdbc:mysql://121.199.31.35:3306/company?characterEncoding=UTF-8
    username: root
    password: 123
    driver-class-name: com.mysql.jdbc.Driver
  thymeleaf:
    prefix: classpath:/templates/

mybatis:
  mapper-locations: classpath:mapper/*.xml
